"""
LGBM Forecaster — LightGBM recursive multi-step forecaster.

Thin wrapper over LightGBM that:
1. Builds lag/rolling features from data
2. Trains a gradient boosting model
3. Recursively predicts future steps (using each prediction as input for next)

Features are generated by praxis.forecast.features module.
"""

from __future__ import annotations

from typing import Optional

import numpy as np
import pandas as pd


class LGBMForecaster:
    """LightGBM recursive forecaster.

    Parameters
    ----------
    n_estimators : int
        Number of boosting rounds, default 200.
    learning_rate : float
        Default 0.05.
    max_depth : int
        Default 6.
    feature_cols : list[str], optional
        Feature column names. If None, auto-detected from data.
    """

    def __init__(
        self,
        n_estimators: int = 200,
        learning_rate: float = 0.05,
        max_depth: int = 6,
        feature_cols: Optional[list[str]] = None,
    ):
        self.n_estimators = n_estimators
        self.learning_rate = learning_rate
        self.max_depth = max_depth
        self.feature_cols = feature_cols
        self._model = None
        self._feature_names: list[str] = []

    def fit(
        self,
        data: pd.DataFrame,
        target_col: str = "value",
        date_col: str = "date",
        feature_cols: Optional[list[str]] = None,
    ) -> "LGBMForecaster":
        """Train the LGBM model.

        Parameters
        ----------
        data : pd.DataFrame
            Training data with features and target.
        target_col : str
            Column name for the target variable.
        feature_cols : list[str], optional
            Override feature columns.
        """
        try:
            import lightgbm as lgb
        except ImportError:
            raise ImportError("lightgbm is required. Install with: pip install lightgbm")

        df = data.dropna(subset=[target_col]).copy()

        # Determine features
        if feature_cols:
            self._feature_names = feature_cols
        elif self.feature_cols:
            self._feature_names = self.feature_cols
        else:
            exclude = {target_col, date_col, "date", "entity"}
            self._feature_names = [c for c in df.columns if c not in exclude and df[c].dtype in ("float64", "int64", "float32", "int32")]

        X = df[self._feature_names].values
        y = df[target_col].values

        self._model = lgb.LGBMRegressor(
            n_estimators=self.n_estimators,
            learning_rate=self.learning_rate,
            max_depth=self.max_depth,
            verbose=-1,
            n_jobs=-1,
        )
        self._model.fit(X, y)

        return self

    def predict(
        self,
        data: pd.DataFrame,
    ) -> np.ndarray:
        """Predict using trained model.

        Parameters
        ----------
        data : pd.DataFrame
            Must contain the same feature columns as training.

        Returns
        -------
        numpy array of predictions.
        """
        if self._model is None:
            raise RuntimeError("Model not fitted. Call .fit() first.")

        X = data[self._feature_names].values
        return self._model.predict(X)

    def predict_recursive(
        self,
        seed_data: pd.DataFrame,
        horizon: int,
        target_col: str = "value",
        feature_builder=None,
    ) -> pd.DataFrame:
        """Recursive multi-step forecast.

        At each step:
        1. Predict the next value
        2. Append it to history
        3. Rebuild features for next step

        Parameters
        ----------
        seed_data : pd.DataFrame
            Historical data to start recursive predictions from.
        horizon : int
            Number of steps to forecast.
        feature_builder : callable, optional
            Function(df) → df_with_features. Used to rebuild features
            after each recursive step.

        Returns
        -------
        DataFrame with forecast values.
        """
        if self._model is None:
            raise RuntimeError("Model not fitted. Call .fit() first.")

        history = seed_data.copy()
        predictions = []

        for step in range(horizon):
            if feature_builder:
                history = feature_builder(history)

            last_row = history.iloc[[-1]]
            X = last_row[self._feature_names].values
            pred = self._model.predict(X)[0]
            pred = max(pred, 0)  # Floor at zero

            # Create next row
            next_row = last_row.copy()
            next_row[target_col] = pred

            if "date" in next_row.columns:
                next_row["date"] = next_row["date"] + pd.Timedelta(days=1)

            predictions.append(
                {
                    "step": step + 1,
                    "forecast": pred,
                    "date": next_row["date"].values[0] if "date" in next_row.columns else step + 1,
                }
            )

            history = pd.concat([history, next_row], ignore_index=True)

        return pd.DataFrame(predictions)

    @property
    def feature_importance(self) -> pd.DataFrame:
        """Return feature importance from the trained model."""
        if self._model is None:
            return pd.DataFrame(columns=["feature", "importance"])
        imp = self._model.feature_importances_
        return (
            pd.DataFrame({"feature": self._feature_names, "importance": imp})
            .sort_values("importance", ascending=False)
            .reset_index(drop=True)
        )
